FROM ocaml/opam:debian-11-ocaml-4.13@sha256:7d28bbe850d9f89a344b6fb9c628dba15127acc9e6cdb1b03f72c1ec985ada4a AS build
RUN sudo apt-get update && sudo apt-get install libev-dev capnproto m4 pkg-config libgmp-dev libffi-dev -y --no-install-recommends
RUN cd ~/opam-repository && git pull origin master && git reset --hard 16ff1304f8ccdd5a8c9fa3ebe906c32ecdd576ee && opam update
COPY --chown=opam \
	ocurrent/current_rpc.opam \
	/src/ocurrent/
WORKDIR /src
RUN opam pin -yn add ./ocurrent
COPY --chown=opam opam-repo-ci-api.opam opam-repo-ci-web.opam /src/
RUN opam install -y --deps-only .
ADD --chown=opam . .
RUN opam config exec -- dune build ./_build/install/default/bin/opam-repo-ci-web

FROM debian:11
RUN apt-get update && apt-get install ca-certificates libev4 dumb-init -y --no-install-recommends
WORKDIR /
ENTRYPOINT ["dumb-init", "/usr/local/bin/opam-repo-ci-web"]
COPY --from=build /src/_build/install/default/bin/opam-repo-ci-web /usr/local/bin/
