version: "3.7"
volumes:
  data:
  capnp-secrets:
secrets:
  opam-repo-ci-github-key:
    external: true
  opam-repo-ci-oauth:
    external: true
  opam-repo-ci-submission-cap:
    external: true
  opam-repo-ci-webhook-secret:
    external: true
services:
  opam-repo-ci:
    image: ocurrent/opam-repo-ci:live
    command: >
      --github-app-id=85861
      --github-private-key-file=/run/secrets/opam-repo-ci-github-key
      --github-account-allowlist="ocaml"
      --confirm=above-average
      --confirm-auto-release=120
      --capnp-address=tcp:opam-repo.ci.ocaml.org:9000
      --github-oauth=/run/secrets/opam-repo-ci-oauth
      --submission-service=/run/secrets/opam-repo-ci-submission-cap
      --github-webhook-secret-file=/run/secrets/opam-repo-ci-webhook-secret
      --verbosity=info
    ports:
      - '9000:9000'
    environment:
      - "CI_PROFILE=production"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    volumes:
      - 'data:/var/lib/ocurrent'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'opam-repo-ci-oauth'
      - 'opam-repo-ci-github-key'
      - 'opam-repo-ci-submission-cap'
      - 'opam-repo-ci-webhook-secret'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
  opam-repo-ci-web:
    image: ocurrent/opam-repo-ci-web:live
    command: >
      --backend=/capnp-secrets/opam-repo-ci-admin.cap
      --verbosity=info
    volumes:
      - 'capnp-secrets:/capnp-secrets:ro'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'

