version: '3.1'
volumes:
  data:
  capnp-secrets:
secrets:
  opam-repo-ci-github-key:
    external: true
  opam-repo-ci-oauth:
    external: true
  ocaml-ci-webhook-secret:
    external: true
services:
  ci:
    image: opam-repo-ci-service
    command: --github-app-id 52344 --github-private-key-file /run/secrets/opam-repo-ci-github-key --github-account-whitelist "kit-ty-kate" --confirm above-average --confirm-auto-release 120 --capnp-address=tcp:ci:9000 --github-oauth /run/secrets/opam-repo-ci-oauth --github-webhook-secret-file /run/secrets/ocaml-ci-webhook-secret
    environment:
      - "CI_PROFILE=production"
      - "PROGRESS_NO_TRUNC=1"
    ports:
      - '8080:8080'
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'opam-repo-ci-oauth'
      - 'opam-repo-ci-github-key'
      - 'ocaml-ci-webhook-secret'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
    networks:
      - default
  web:
    image: opam-repo-ci-web
    command: --backend /capnp-secrets/opam-repo-ci-admin.cap --listen-prometheus=9090
    ports:
      - '80:8090'
    volumes:
      - 'capnp-secrets:/capnp-secrets:ro'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
    networks:
      - default
